[workspace]
resolver = "2"
members = ["runner", "shared", "v0-0-5", "v0-0-6"]

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }

starknet = { git = "https://github.com/xJonathanLEI/starknet-rs", rev = "d980869" }
thiserror = "1.0.59"
url = "2.5.0"
regex = "1.10.4"
clap = { version = "4.5.4", features = ["derive", "env"] }
serde = { version = "1.0.160", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.96", default-features = false, features = [
    "alloc",
    "raw_value",
] }
serde_with = { version = "2.3.2", default-features = false, features = [
    "alloc",
    "macros",
] }

starknet-crypto = "0.6.2"

serde_json_pythonic = { version = "0.1.2", default-features = false, features = [
    "alloc",
    "raw_value",
] }
hex-literal = "0.4.1"
tracing = "0.1.40"
base64 = { version = "0.21.0", default-features = false, features = ["alloc"] }
async-trait = "0.1.68"
auto_impl = "1.0.1"
log = "0.4.19"

starknet-signers = "0.8.0"
sha3 = { version = "0.10.7", default-features = false }
colored = "2.1.0"
flate2 = "1.0.30"
