[workspace]
members = ["runner", "shared", "utils", "v0-0-5", "v0-0-6"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
auto_impl = "1.2.0"
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
clap = { version = "4.5.7", features = ["derive", "env"] }
colored = "2.1.0"
flate2 = "1.0.30"
hex-literal = "0.4.1"
proptest = "1.4.0"
prefix-hex = "0.7.1"
rand = "0.8.5"
regex = "1.10.5"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.203", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.117", default-features = false, features = [
    "alloc",
    "raw_value",
] }
serde_json_pythonic = { version = "0.1.2", default-features = false, features = [
    "alloc",
    "raw_value",
] }
serde_with = { version = "3.8.1", default-features = false, features = [
    "alloc",
    "macros",
] }
sha3 = { version = "0.10.8", default-features = false }
starknet-crypto = "0.6.2"
starknet-signers = "0.8.0"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.1"
