[workspace]
resolver = "2"
members = ["runner", "t8n", "t9n", "versions"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
auto_impl = "1.2.0"
clap = { version = "4.5.9", features = ["derive", "env"] }
colored = "2.1.0"
lambdaworks-math = { version = "0.7.0", default-features = false }
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.120", default-features = false, features = [
    "alloc",
    "raw_value",
] }
serde_json_pythonic = "0.1.2"
starknet-types-rpc = { path = "/home/piotrstec/dev/typesrs_forked/types-rs/crates/starknet-types-rpc" }
starknet-types-core = { path = "/home/piotrstec/dev/typesrs_forked/types-rs/crates/starknet-types-core" }
# starknet-types-rpc = { path = "/home/filipg/dev/forks-latest/types-rs/crates/starknet-types-rpc" } // working
# starknet-types-core = { path = "/home/filipg/dev/forks-latest/types-rs/crates/starknet-types-core" } // working 
# starknet-types-rpc = { path = "/home/filipg/forks/types-rs/crates/starknet-types-rpc" } // deprecated
# starknet-types-core = { path = "/home/filipg/forks/types-rs/crates/starknet-types-core" } // deprecated
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.2"
serde_with = "3.8.3"
rand = "0.8.5"
regex = "1.10.5"
crypto-bigint = "0.5.5"
sha3 = "0.10.8"
