[workspace]
members = ["example","sample"]

[workspace.package]
edition = "2023_10"
version = "0.1.0"

[workspace.dependencies]
starknet = "2.6.3"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.24.0" }

