[sncast.default]

# account = "sepolia1"
# accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
# url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/6sv_IrvSsTZ3fsrODvt0cc0cMLwgLVaP"

account = "argent_pm"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:9545"
