kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
      - containerPort: 30011
        hostPort: 30011
        protocol: TCP
      - containerPort: 30021
        hostPort: 30021
        protocol: TCP
      - containerPort: 30002
        hostPort: 30002
        protocol: TCP
      - containerPort: 30012
        hostPort: 30012
        protocol: TCP
      - containerPort: 30022
        hostPort: 30022
        protocol: TCP
      - containerPort: 30031
        hostPort: 30031
        protocol: TCP
      - containerPort: 30032
        hostPort: 30032
        protocol: TCP
      - containerPort: 30033
        hostPort: 30033
        protocol: TCP
      - containerPort: 30034
        hostPort: 30034
        protocol: TCP
