apiVersion: v1
kind: Pod
metadata:
  name: papyrus-1
spec:
  initContainers:
    - name: wait-for-anvil
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z anvil-service 8545; do echo waiting for anvil; sleep 2; done;",
        ]
  containers:
    - name: papyrus-1
      image: ghcr.io/starkware-libs/papyrus:dev
      args:
        - "--base_layer.node_url"
        - "http://anvil-service:8545"
      ports:
        - containerPort: 8080
        - containerPort: 8081
      volumeMounts:
        - name: data-volume
          mountPath: /app/data
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: papyrus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: papyrus-service-1
spec:
  type: NodePort
  selector:
    app: papyrus-1
  ports:
    - name: rpc-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30033
    - name: rpc-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30034
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papyrus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
