[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
colored.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
v0-0-5 = { path = "../v0-0-5" }
v0-0-6 = { path = "../v0-0-6" }
