apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pathfinder
  - anvil
  - madara
  - juno
  - papyrus

secretGenerator:
  - name: secret
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
